# Generated by Django 3.2 on 2021-06-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyremedy',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
