# Generated by Django 3.2 on 2021-05-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210507_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
