# Generated by Django 3.2 on 2021-06-01 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210531_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='remedies',
        ),
        migrations.CreateModel(
            name='BasketRemedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_remedies', to='api.basket')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.pharmacy')),
                ('remedy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.remedy')),
            ],
            options={
                'db_table': 'basket_remedy',
            },
        ),
    ]
