# Generated by Django 3.2 on 2021-06-12 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210601_1932'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='authuser_ptr',
        ),
        migrations.AlterField(
            model_name='pharmacyremedy',
            name='remedy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacies', to='api.remedy'),
        ),
    ]
